// One-time seed data, curated from real Outlook items so the command center
// starts with meaningful content. The /api/seed route upserts these into
// Supabase. IDs are stable so re-running is safe (no duplicates).

import type { Email, Task } from "./types";

type SeedEmail = Omit<Email, "created_at">;
type SeedTask = Omit<Task, "created_at">;

export const SEED_EMAILS: SeedEmail[] = [
  {
    id: "email_seed_qualcomm",
    subject: "Re: Building Together: Robotics & AI Competition with Qualcomm",
    from_name: "Pratik Ghosh Dastidar",
    from_email: "pratik.d@getsetlearn.info",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "9 June confirmed for the next discussion on the Robotics & AI competition with Qualcomm / Anand / KIPS.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_trainer",
    subject: "Trainer Allocation – Location Mapping Required",
    from_name: "HR – Get Set Learn",
    from_email: "hr@getsetlearn.info",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "High priority. Trainers in place across regions (Hyderabad, TN, Bangalore, Mumbai, North). Location mapping needed.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_arduino",
    subject: "Re: Arduino Orders",
    from_name: "Rubi Prasad (Arduino)",
    from_email: "r.prasad@ext.arduino.cc",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "Stock status attached. HS code issue on Arduino UNO Q; suggestion to add Arduino Student Kit to the Edutech order.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_gallabox",
    subject: "Approval Request for Gallabox Enablement",
    from_name: "Vidyashree BM",
    from_email: "vidya.m@getsetlearn.info",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "Requesting approval for Gallabox (WhatsApp automation / drip campaigns) to strengthen lead nurturing.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_tcl",
    subject: "Re: GSL-TCL Platform Backend Meeting",
    from_name: "Namrata S",
    from_email: "namrata.s@getsetlearn.info",
    received_date: "2026-06-02",
    tag: "action",
    summary:
      "Needs TCL platform backend login credentials to upload case studies and manage evaluation rubrics.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_abp",
    subject: "ABP — Why ABP + GSL? (partnership deck)",
    from_name: "Pratik Ghosh Dastidar",
    from_email: "pratik.d@getsetlearn.info",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "Draft pitch deck for an ABP + GSL future-skills partnership (NEP 2020 angle). Needs review.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_aptech_recap",
    subject: "Your meeting recap - GSL-Aptech Connect (Follow up)",
    from_name: "Fireflies.ai",
    from_email: "fred@fireflies.ai",
    received_date: "2026-06-03",
    tag: "fyi",
    summary:
      "Recap of the GSL-Aptech / Qualcomm follow-up meeting (Jun 3, 4:00 PM IST). Notes available.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
  {
    id: "email_seed_prismix",
    subject: "Re: Gen AI tools - Prismix / Aptech Gen AI",
    from_name: "Abir (Aptech)",
    from_email: "abir@aptech.co.in",
    received_date: "2026-06-03",
    tag: "action",
    summary:
      "Magnific (Premium+) is ~INR 3000/month; for a 3-month course the pass-through cost is ~10k+. Needs pricing decision.",
    draft: null,
    actions: [],
    status: "pending",
    resolved_date: null,
    m365_message_id: null,
  },
];

export const SEED_TASKS: SeedTask[] = [
  {
    id: "task_seed_qualcomm",
    title: "Confirm 9 June meeting — Robotics & AI Competition with Qualcomm",
    project: "Partnerships",
    priority: "high",
    status: "active",
    note: "Pratik confirmed 9 June. Align internal team + agenda.",
    actions: [],
    added_date: "2026-06-03",
    done_date: null,
  },
  {
    id: "task_seed_gallabox",
    title: "Approve or decline Gallabox enablement request",
    project: "GSL Innovation",
    priority: "high",
    status: "active",
    note: "Vidya's WhatsApp automation proposal — evaluate broader use cases first.",
    actions: [],
    added_date: "2026-06-03",
    done_date: null,
  },
  {
    id: "task_seed_arduino",
    title: "Resolve Arduino UNO Q HS-code issue with Vishwanath / Arduino",
    project: "Operations",
    priority: "high",
    status: "active",
    note: "Blocking bulk import. Confirm Science Kit move to Kaynes order.",
    actions: [],
    added_date: "2026-06-03",
    done_date: null,
  },
  {
    id: "task_seed_trainer",
    title: "Complete trainer allocation location mapping (HR)",
    project: "Operations",
    priority: "high",
    status: "active",
    note: null,
    actions: [],
    added_date: "2026-06-03",
    done_date: null,
  },
  {
    id: "task_seed_tcl",
    title: "Get TCL platform backend credentials to Namrata",
    project: "Talk & Learn",
    priority: "medium",
    status: "active",
    note: "Needed to upload case studies + manage rubrics.",
    actions: [],
    added_date: "2026-06-02",
    done_date: null,
  },
  {
    id: "task_seed_abp",
    title: "Review ABP + GSL partnership deck from Pratik",
    project: "Partnerships",
    priority: "medium",
    status: "active",
    note: null,
    actions: [],
    added_date: "2026-06-03",
    done_date: null,
  },
];
